# Generated by Django 4.2.6 on 2023-10-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.FloatField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='RecipeRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='0')),
                ('in_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_inventory.ingredients')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_inventory.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_inventory.ingredients')),
            ],
        ),
    ]
